// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcR32-ypXrphkc4C5hUX4UHHjeDGZOHv4',
    appId: '1:567617166098:web:5797ce5d59ac6ac07e71cb',
    messagingSenderId: '567617166098',
    projectId: 'car-rental-d4f9d',
    authDomain: 'car-rental-d4f9d.firebaseapp.com',
    storageBucket: 'car-rental-d4f9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB2nwm20GSEPpIGyyIZBbjCk-zb3ULTQ4',
    appId: '1:567617166098:android:42dc168cd43805f07e71cb',
    messagingSenderId: '567617166098',
    projectId: 'car-rental-d4f9d',
    storageBucket: 'car-rental-d4f9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNEYpLxir_JBhqLJWmTgm-6M7872ka_O8',
    appId: '1:567617166098:ios:28e570fa035063507e71cb',
    messagingSenderId: '567617166098',
    projectId: 'car-rental-d4f9d',
    storageBucket: 'car-rental-d4f9d.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNEYpLxir_JBhqLJWmTgm-6M7872ka_O8',
    appId: '1:567617166098:ios:28e570fa035063507e71cb',
    messagingSenderId: '567617166098',
    projectId: 'car-rental-d4f9d',
    storageBucket: 'car-rental-d4f9d.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcR32-ypXrphkc4C5hUX4UHHjeDGZOHv4',
    appId: '1:567617166098:web:1d21c5481a794fe67e71cb',
    messagingSenderId: '567617166098',
    projectId: 'car-rental-d4f9d',
    authDomain: 'car-rental-d4f9d.firebaseapp.com',
    storageBucket: 'car-rental-d4f9d.firebasestorage.app',
  );
}
